order:
 - FFVII            # 1
 - FFVIIR           # 2
 - FFVII            # 3
 - FFX              # 4
 - FFVIII           # 5
 - FFX              # 6
 - FFIX             # 7
 - FFX Pbirdman Mod # 8
 - FFX-2            # 9
 - Intermission     # 10
 - FFXII            # 11
 - FFX              # 12
 - FFXIII           # 13
 - FFXIII-2         # 14
 - FFXIII-3         # 15
 - FFX              # 16
 - FFX-2            # 17
 - FFXV             # 18
 - Birthday         # 19

  #Template:
  #<Name of Game/Video> (NEEDS to match entry in 'order' section)       **REQUIRED**
  #  type:          playlist or video                                   **REQUIRED**
  #  id:            URL id of playlist or video                         **REQUIRED**
  #  loops:         Number of consective plays                          DEFAULT: 1
  #  beginning:     Episode number to start in the playlist             DEFAULT: 1
  #  exclude:       List of episode numbers to exclude from playing     DEFAULT: NONE
  #  end:           Last episode to play in the playlist                DEFAULT: LAST VIDEO
  #  videoformatid: YT video format ID to download                      DEFAULT: BESTVIDEO
  #  audioformatid: YT audio format ID to download                      DEFAULT: BESTAUDIO

sections:
  FFVII:
    type: playlist
    id: PL9wpzJw8GKy6jduVjw_TFkQleVQVQmjZ1
    loops: 1
    beginning: 2
    ending: 90
  FFVIIR:
    type: playlist
    id: PL9wpzJw8GKy5NkqIPTrpBdKIq7TlEgdVB
    loops: 1
    ending: 88
  FFVIII:
    type: playlist
    id: PL9wpzJw8GKy7-VIz9_kYjaXYyqEerexxo
    loops: 2
    ending: 76
  FFIX:
    type: playlist
    id: PL9wpzJw8GKy7_vGHBnsIf99WoE1PV8fib
    loops: 2
    ending: 83
  FFX:
    type: playlist
    id: PL9wpzJw8GKy74rLqQv7OH9v94Hj8qQWps
    ending: 133
  FFX-2:
    type: playlist
    id: PL9wpzJw8GKy4iBmZcKF0HYd8xF0FmBueF
    exclude:
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
    ending: 104
  FFXII:
    type: playlist
    id: PL9wpzJw8GKy4PLI_hOOTLIRbZgc380SoJ
    ending: 132
    #videoformatid: 137
  FFXIII:
    type: playlist
    id: PL9wpzJw8GKy5MRpDdYVvssMRgGjVLlA0K
    loops: 2
    #videoformatid: 137
    ending: 95
  FFXIII-2:
    type: playlist
    id: PL9wpzJw8GKy4XCYWG7RyNv62Y24vgxVcR
    #videoformatid: 137
    ending: 73
  FFXIII-3:
    type: playlist
    id: PL9wpzJw8GKy5X2REI5pL7ipD8anVgAnsG
    #videoformatid: 137
    ending: 92
  FFXV:
    type: playlist
    id: PL9wpzJw8GKy7Uh35q-_CDXJv_4jf4G8du
    #videoformatid: 137
    ending: 77
  Intermission:
    type: video
    id: pUVs2fly-is
  Birthday:
    type: video
    id: I81JBsKzhbU
  FFX Pbirdman Mod:
    type: playlist
    id: PL9wpzJw8GKy7RblnEe2iU-GsWrdpdedKD
    ending: 44
